### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by INSide-734** [longchengguxiao/nonebot_plugin_pvz#7]
01-31 19:02:23 [ERROR] nonebot | Failed to import "zhenxun_plugins_pvz"
Traceback (most recent call last):
  File "/root/test/zhenxun/bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--hUX7pyy-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--hUX7pyy-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--hUX7pyy-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--hUX7pyy-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--hUX7pyy-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/test/zhenxun/extensive_plugin/zhenxun_plugins_pvz/__init__.py", line 62
    global_config = nonebot.get_driver().config
                  ^
SyntaxError: invalid syntax

**Comment by longchengguxiao** [comment]
前所未见的报错，为什么会报拼写错误啊

**Comment by longchengguxiao** [comment]
你的安装命令是什么

**Comment by INSide-734** [comment]
git pull下运行

**Comment by INSide-734** [comment]
我少打个括号麻了

**Comment by longchengguxiao** [comment]
> 我少打个括号麻了

哈哈哈，我正想看看zhenxun那边的启动方式呢

**Comment by INSide-734** [comment]
什么时候适配真寻（

**Comment by longchengguxiao** [comment]
主要是我也没用过真寻bot，讲道理是都可以配适的，你先试试能不能正常运行，不能的话就再告诉我，我有时间看看
